eureka:
  client:
    service-url:
      defaultZone: http://localhost:2181/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 10
server:
  port: 2184
spring:
  application:
    name: service-ribbon