foo:
  foo versino dev
eureka:
  service:
    port:
      center: 2181
      base: 2191
      feign: 2192
      ribbon: 2193
    name:
      base: service-base
      feign: service-feign
      ribbon: service-ribbon
  hostname:
    localhost
my-rabbitmq:
  host: localhost
  port: 15672
  username: qicai
  password: qicai123
