server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaozhaoosc/spring-boot-learn.git
          search-paths: cloud-config/cloud-config-repo
      label: master
  application:
    name: cloud-config-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2181/eureka/